# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import two_tower_pb2 as two__tower__pb2

GRPC_GENERATED_VERSION = '1.78.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in two_tower_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class TwoTowerServiceStub(object):
    """Two-Tower communication service
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.ValidateAction = channel.unary_unary(
                '/ippoc.two_tower.TwoTowerService/ValidateAction',
                request_serializer=two__tower__pb2.ActionCandidate.SerializeToString,
                response_deserializer=two__tower__pb2.ValidationDecision.FromString,
                _registered_method=True)
        self.BatchValidateActions = channel.unary_unary(
                '/ippoc.two_tower.TwoTowerService/BatchValidateActions',
                request_serializer=two__tower__pb2.BatchValidationRequest.SerializeToString,
                response_deserializer=two__tower__pb2.BatchValidationResponse.FromString,
                _registered_method=True)
        self.GetValidationStats = channel.unary_unary(
                '/ippoc.two_tower.TwoTowerService/GetValidationStats',
                request_serializer=two__tower__pb2.ValidationStatsRequest.SerializeToString,
                response_deserializer=two__tower__pb2.ValidationStatsResponse.FromString,
                _registered_method=True)


class TwoTowerServiceServicer(object):
    """Two-Tower communication service
    """

    def ValidateAction(self, request, context):
        """Send action candidate for validation
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def BatchValidateActions(self, request, context):
        """Batch validation for multiple candidates
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetValidationStats(self, request, context):
        """Get validation statistics
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TwoTowerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'ValidateAction': grpc.unary_unary_rpc_method_handler(
                    servicer.ValidateAction,
                    request_deserializer=two__tower__pb2.ActionCandidate.FromString,
                    response_serializer=two__tower__pb2.ValidationDecision.SerializeToString,
            ),
            'BatchValidateActions': grpc.unary_unary_rpc_method_handler(
                    servicer.BatchValidateActions,
                    request_deserializer=two__tower__pb2.BatchValidationRequest.FromString,
                    response_serializer=two__tower__pb2.BatchValidationResponse.SerializeToString,
            ),
            'GetValidationStats': grpc.unary_unary_rpc_method_handler(
                    servicer.GetValidationStats,
                    request_deserializer=two__tower__pb2.ValidationStatsRequest.FromString,
                    response_serializer=two__tower__pb2.ValidationStatsResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'ippoc.two_tower.TwoTowerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('ippoc.two_tower.TwoTowerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class TwoTowerService(object):
    """Two-Tower communication service
    """

    @staticmethod
    def ValidateAction(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ippoc.two_tower.TwoTowerService/ValidateAction',
            two__tower__pb2.ActionCandidate.SerializeToString,
            two__tower__pb2.ValidationDecision.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def BatchValidateActions(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ippoc.two_tower.TwoTowerService/BatchValidateActions',
            two__tower__pb2.BatchValidationRequest.SerializeToString,
            two__tower__pb2.BatchValidationResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetValidationStats(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/ippoc.two_tower.TwoTowerService/GetValidationStats',
            two__tower__pb2.ValidationStatsRequest.SerializeToString,
            two__tower__pb2.ValidationStatsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
