
import pytest
from fastapi.testclient import TestClient
from src.ippoc.soma.server import app

client = TestClient(app)

def test_api_key_strength():
    """
    Verify that API keys generated by Soma meet security requirements:
    - Not a UUIDv4 (which has insufficient entropy for long-term keys)
    - Length > 32 characters (indicating high entropy, e.g. from secrets.token_urlsafe(32))
    """
    response = client.post("/v1/auth/issue")
    assert response.status_code == 200
    data = response.json()

    api_key = data["api_key"]

    # Check length (UUID is 36 chars, token_urlsafe(32) is approx 43 chars)
    # We want to force a change away from UUID, so let's assert it's longer than a UUID or has different structure
    # UUID format: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx

    is_uuid = False
    try:
        import uuid
        uuid.UUID(api_key)
        is_uuid = True
    except ValueError:
        is_uuid = False

    if is_uuid:
        pytest.fail(f"API Key '{api_key}' is a UUID, which is considered weak for this context. Expected a cryptographically strong token.")

    assert len(api_key) > 40, f"API Key '{api_key}' is too short ({len(api_key)} chars). Expected > 40."
