# Kbuild file for IPPOC kernel module

obj-m := ippoc_sensor.o

# Point to Linux kernel source (using local linux-master)
KDIR ?= $(PWD)/../../linux-master

all:
	$(MAKE) -C $(KDIR) M=$(PWD) modules

clean:
	$(MAKE) -C $(KDIR) M=$(PWD) clean

install:
	$(MAKE) -C $(KDIR) M=$(PWD) modules_install

.PHONY: all clean install
